name: Secret Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  secret-scan:
    name: Trufflehog Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # Trufflehog scans commit history, so we need depth 0

      - name: Run Trufflehog Scanner
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
